### ISSUE TITLE
Missing (lcd) Display feed for Dm800se

### ISSUE THREAD

**Issue by neoatomic** [oe-alliance/enigma2-display-skins#23]
@atvcaptain 
Did a fresh install yesterday, (latest openatv5.3) and noted that the "Display" feed was missing for the LCD screen of my dreambox 800se. (its enabled in the filter feed section.)

The Solo4k display feed is working fine. But 1 skin still needs a prev.jpg for preview. 
https://github.com/oe-alliance/enigma2-display-skins/blob/master/skins/display480/OE-A_LCDSkin_7/prev.png

**Comment by atvcaptain** [comment]
yes one picture is missing , then you can make a good photo please add :)

dm optional display skin 96 pixel 800se etc or 128 pixel we dont have skins for this model at this time, the 128 folder was for vu vfd display not for the dm color display !

**Comment by neoatomic** [comment]
Ok, previously there where lcd skins on the feed for my 800se, so that confused me. 
Just did a PR, included 2x 96pxl lcd skins and a new picture for the lcd_skin_7 480pxl. :)

**Comment by atvcaptain** [comment]
fine :)
